#!/usr/bin/env node
/**
 * Convert .txt prompt files to .ts exported string constants.
 * Run from project root:
 *   node scripts/prompts-to-ts.mjs
 *
 * This generates:
 *   amplify/functions/llm-dialogue-function/promptStrings.ts
 *   amplify/functions/llm-scoring-function/promptStrings.ts
 */
import { readFileSync, writeFileSync } from "fs";

function escapeForTemplate(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// ── Dialogue prompts ────────────────────────────────────────────────────
const dialogueDir = "amplify/functions/llm-dialogue-function/prompts";
const dTask1 = readFileSync(`${dialogueDir}/task1/baseInstructions.txt`, "utf8").trim();
const dTask2 = readFileSync(`${dialogueDir}/task2/baseInstructions.txt`, "utf8").trim();
const dTask3 = readFileSync(`${dialogueDir}/task3/baseInstructions.txt`, "utf8").trim();

writeFileSync(
  "amplify/functions/llm-dialogue-function/promptStrings.ts",
  `// AUTO-GENERATED by scripts/prompts-to-ts.mjs — do not edit manually.
// Regenerate: node scripts/prompts-to-ts.mjs

type Scenario = "task1" | "task2" | "task3";

export const DIALOGUE_PROMPTS: Record<Scenario, string> = {
  task1: \`${escapeForTemplate(dTask1)}\`,
  task2: \`${escapeForTemplate(dTask2)}\`,
  task3: \`${escapeForTemplate(dTask3)}\`,
};
`,
  "utf8"
);

console.log("✓ wrote amplify/functions/llm-dialogue-function/promptStrings.ts");

// ── Scoring prompts ─────────────────────────────────────────────────────
const scoringDir = "amplify/functions/llm-scoring-function/prompts";
const sTask1 = readFileSync(`${scoringDir}/task1/scoringPrompt.txt`, "utf8").trim();
const sTask2 = readFileSync(`${scoringDir}/task2/scoringPrompt.txt`, "utf8").trim();
const sTask3 = readFileSync(`${scoringDir}/task3/scoringPrompt.txt`, "utf8").trim();

writeFileSync(
  "amplify/functions/llm-scoring-function/promptStrings.ts",
  `// AUTO-GENERATED by scripts/prompts-to-ts.mjs — do not edit manually.
// Regenerate: node scripts/prompts-to-ts.mjs

type Scenario = "task1" | "task2" | "task3";

export const SCORING_PROMPTS: Record<Scenario, string> = {
  task1: \`${escapeForTemplate(sTask1)}\`,
  task2: \`${escapeForTemplate(sTask2)}\`,
  task3: \`${escapeForTemplate(sTask3)}\`,
};
`,
  "utf8"
);

console.log("✓ wrote amplify/functions/llm-scoring-function/promptStrings.ts");
